version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - server
    command: yarn start

  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - ./server:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env

volumes:
  qdrant_storage: